### ISSUE TITLE
TypeError on runtime

### ISSUE THREAD

**Issue by reckoner165** [amoghpj/swar-synthesizer#4]
Here's the trace

```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    synth.convert(options.infilename,outfilename,options.basefreq)
  File "swar-synthesizer/src/swar_synthesizer.py", line 256, in convert
    create_and_save(swar_string,save_name=outf_p,m_duration=0.5,base_freq=int(freq))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Tried removing the `base_freq` argument to push it to default but that throws a different error.

**Comment by amoghpj** [comment]
Fixed the way I process default arguments in convert(). Let me know if this fixes the error.

**Comment by reckoner165** [comment]
Works!
